"""add fraud columns to transaction

Revision ID: b5a4f39ca462
Revises: d63eb3a3562c
Create Date: 2026-02-01 12:49:06.396134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a4f39ca462'
down_revision: Union[str, Sequence[str], None] = 'd63eb3a3562c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_profiles_id'))

    op.drop_table('voice_profiles')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fraud_reason', sa.String(), nullable=True))
        batch_op.drop_column('is_fraud')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fraud', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('fraud_reason')

    op.create_table('voice_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('embedding', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_profiles_id'), ['id'], unique=False)

    # ### end Alembic commands ###
