"""Add payment_requests table

Revision ID: d05fd66f45c6
Revises: b5a4f39ca462
Create Date: 2026-02-04 11:12:42.090236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05fd66f45c6'
down_revision: Union[str, Sequence[str], None] = 'b5a4f39ca462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_profiles_id'))

    op.drop_table('voice_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('embedding', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_profiles_id'), ['id'], unique=False)

    # ### end Alembic commands ###
