"""Add token blacklist table

Revision ID: d63eb3a3562c
Revises: 6f9ecde5e706
Create Date: 2025-12-14 14:53:36.534493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63eb3a3562c'
down_revision: Union[str, Sequence[str], None] = '6f9ecde5e706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('blacklisted_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blacklist_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_token'))
        batch_op.drop_index(batch_op.f('ix_token_blacklist_id'))

    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
